services:
  postgresql:
    container_name: security-postgres
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  pgdata: